= Commit Notes = (#30)
testing:
- rename echo tests
- add address tests
- type callback + member tests
- fake memory reader

refactor:
- towards legit error handling
- adapth echo and address commands
- uncaught exceptions can now crash the repl
- adjust bogus tests to expect exceptions
- add preliminary pipe tests for echo and address
- repl catches all SDB related errors
- tprog testing infrastructure as common code
- one_member test object equality

fix:
- member command passed scalar input throws error instead of crashing
- member command passed bogus member throws error instead of crashing
- pyfilter handle SyntaxError and TypeError

style:
- yapf format the tests directory
- pylint test directory
- add License text in test files

travis:
- add yapf checks for testing directory

doc:
- no longer using black

= Example Output =

* Command not found:
```
> dawefasdf
sdb: cannot recognize command: dawefasdf
```

* Incorrect arguments passed to command's argparse
```
> member
usage: member [-h] <member> [<member> ...]
member: error: the following arguments are required: <member>
```

*  Handle incorrect input to echo
```
> echo asdf
sdb: echo: invalid input: asdf
```

* Handle symbol not found in address command
```
> address as3
sdb: address: symbol not found: as3
```

* Always print the command name used in the error message
```
> echo asdf
sdb: echo: invalid input: asdf
> cc asdf
sdb: cc: invalid input: asdf
> addr as2
sdb: addr: symbol not found: as2
> address as3
sdb: address: symbol not found: as3
```

* Handle drgn value-objects uniformly in address command
```
> echo 10 | addr
(void *)0xa
```

* Handle scalar types passed to member command
```
> addr zfs_flags | member test
sdb: member: 'int' is not a structure or union
```

* Handle incorrect member for member command
```
> addr spa_namespace_avl | member avl_raat
sdb: member: 'avl_tree_t' has no member 'avl_raat'
```

* Handle pyfilter syntax error:
```
>  echo 0 1 | pyfilter obj.address_ asdf asdf
sdb: pyfilter: invalid syntax:
	obj.address_ asdf asdf
	                ^
>
```

* Handle pyfilter attribute error:
```
> echo 0 1 | pyfilter obj.addres
sdb: pyfilter: '_drgn.Object' object has no attribute 'addres'
```

* Handle pyfilter type error:
```
> echo 0 1 | pyfilter obj == 0
sdb: pyfilter: invalid operands to comparison ('void *' and 'int')
```